<?php
namespace Tests\Feature;
use App\Models\{AutomationRule,Pqr,PqrTag,ResponseTemplate,TipoPqr,User}; use App\Notifications\PqrEventNotification; use Illuminate\Foundation\Testing\RefreshDatabase; use Illuminate\Support\Facades\Notification; use Tests\Concerns\CreatesInstitutionalContext; use Tests\TestCase;
class PqrComplementaryFeaturesTest extends TestCase { use CreatesInstitutionalContext, RefreshDatabase;
 public function test_manager_can_create_tools_and_rule_auto_assigns():void{[$organizacion,$copropiedad]=$this->createInstitutionalContext();Notification::fake();$admin=User::factory()->create(['role'=>'admin']);$resident=User::factory()->create(['role'=>'residente']);$this->createContextualIdentity($admin,$organizacion,$copropiedad,'admin',['gestion.herramientas_gestionar','pqrs.gestionar']);$this->createContextualIdentity($resident,$organizacion,$copropiedad,'residente',['pqrs.crear']);$type=TipoPqr::factory()->create();$this->actingAsContextual($admin)->post(route('management.templates.store'),['name'=>'Acuse','body'=>'Hemos recibido su solicitud.'])->assertRedirect();$this->post(route('management.tags.store'),['name'=>'Urgente','color'=>'#ff0000'])->assertRedirect();$this->post(route('management.rules.store'),['name'=>'Auto','tipo_pqr_id'=>$type->id,'assign_to_id'=>$admin->id,'set_status'=>'en_revision'])->assertRedirect();$this->assertDatabaseCount('response_templates',1);$this->assertDatabaseCount('pqr_tags',1);$this->actingAsContextual($resident)->post(route('pqrs.store'),['asunto'=>'Automática','descripcion'=>'Debe asignarse automáticamente.','fecha_radicacion'=>today()->format('Y-m-d'),'tipo_pqr_id'=>$type->id]);$this->assertDatabaseHas('pqrs',['assigned_to_id'=>$admin->id,'estado'=>'en_revision']);}
 public function test_resident_can_rate_answered_pqr():void{[$organizacion,$copropiedad]=$this->createInstitutionalContext();$resident=User::factory()->create(['role'=>'residente']);$this->createContextualIdentity($resident,$organizacion,$copropiedad,'residente',['pqrs.ver_propias']);$pqr=Pqr::factory()->create(['user_id'=>$resident->id,'estado'=>'respondida']);$this->actingAs($resident)->post(route('pqrs.survey.store',$pqr),['rating'=>5,'comment'=>'Excelente'])->assertRedirect();$this->assertDatabaseHas('satisfaction_surveys',['pqr_id'=>$pqr->id,'rating'=>5]);}
 public function test_admin_can_update_residential_unit_and_view_audit():void{[$organizacion,$copropiedad]=$this->createInstitutionalContext();$admin=User::factory()->create(['role'=>'admin']);$resident=User::factory()->create(['role'=>'residente']);$this->createContextualIdentity($admin,$organizacion,$copropiedad,'admin',['residentes.gestionar','auditoria.ver']);$this->createContextualIdentity($resident,$organizacion,$copropiedad,'residente',[]);$this->actingAs($admin)->patch(route('management.residents.update',$resident),['tower'=>'B','unit'=>'202'])->assertRedirect();$this->assertDatabaseHas('users',['id'=>$resident->id,'tower'=>'B','unit'=>'202']);$this->get(route('management.audit'))->assertOk()->assertSee('management.residents.update');}
 public function test_reminder_command_notifies_upcoming_cases():void{Notification::fake();$resident=User::factory()->create();$pqr=Pqr::factory()->create(['user_id'=>$resident->id,'estado'=>'radicada','fecha_limite_respuesta'=>today()->addDay()]);$this->artisan('pqrs:send-reminders')->assertSuccessful();Notification::assertSentTo($resident,PqrEventNotification::class);$this->assertNotNull($pqr->fresh()->last_reminder_at);}
}
