<?php
namespace Tests\Feature;
use App\Models\Pqr;
use App\Models\Copropiedad;
use App\Models\Organizacion;
use App\Models\Rol;
use App\Models\SiteSetting;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Notification;
use Tests\TestCase;
class PqrMediumFeaturesTest extends TestCase {
    use RefreshDatabase;
    protected function setUp(): void { parent::setUp(); $organizacion=Organizacion::create(['nombre'=>'Inicial','estado'=>'activa']);$copropiedad=Copropiedad::create(['organizacion_id'=>$organizacion->id,'nombre'=>'Inicial','estado'=>'activa']);$settings=SiteSetting::create(['nombre_conjunto'=>'Inicial','color_principal'=>'#12382f','dias_respuesta'=>15]);$settings->organizacion()->associate($organizacion);$settings->copropiedad()->associate($copropiedad);$settings->save();foreach(['admin','gestor','apoyo','auditor','residente'] as $clave)Rol::create(['clave'=>$clave,'nombre'=>ucfirst($clave),'ambito_aplicable'=>'copropiedad','estado'=>'activo']); }
    public function test_internal_comments_are_private(): void { $manager=User::factory()->create(['role'=>'gestor']);$resident=User::factory()->create(['role'=>'residente']);$pqr=Pqr::factory()->create(['user_id'=>$resident->id]);$this->actingAs($manager)->post(route('pqrs.comments.store',$pqr),['body'=>'Nota privada del equipo'])->assertRedirect();$this->actingAs($resident)->get(route('pqrs.show',$pqr))->assertDontSee('Nota privada del equipo');$this->assertDatabaseHas('pqr_internal_comments',['pqr_id'=>$pqr->id,'body'=>'Nota privada del equipo']); }
    public function test_manager_can_apply_quick_action(): void { Notification::fake();$manager=User::factory()->create(['role'=>'gestor']);$pqr=Pqr::factory()->create(['estado'=>'radicada']);$this->actingAs($manager)->patch(route('pqrs.quick-update',$pqr),['estado'=>'en_revision','assigned_to_id'=>$manager->id])->assertRedirect();$this->assertDatabaseHas('pqrs',['id'=>$pqr->id,'estado'=>'en_revision','assigned_to_id'=>$manager->id]);$this->assertDatabaseHas('pqr_activities',['pqr_id'=>$pqr->id,'action'=>'quick_action']); }
    public function test_reports_export_csv_excel_and_pdf(): void { $manager=User::factory()->create(['role'=>'gestor']);Pqr::factory()->create(['asunto'=>'Informe especial']);$this->actingAs($manager)->get(route('reports.csv'))->assertOk()->assertHeader('content-type','text/csv; charset=UTF-8');$this->get(route('reports.xlsx'))->assertOk()->assertHeader('content-type','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');$this->get(route('reports.pdf'))->assertOk()->assertHeader('content-type','application/pdf'); }
    public function test_user_can_update_profile_and_password(): void { $user=User::factory()->create(['password'=>'clave-anterior']);$this->actingAs($user)->put(route('profile.update'),['name'=>'Nombre Actualizado','email'=>'nuevo@example.com','current_password'=>'clave-anterior','password'=>'NuevaClave123','password_confirmation'=>'NuevaClave123'])->assertSessionHasNoErrors();$this->assertTrue(Hash::check('NuevaClave123',$user->fresh()->password));$this->assertSame('Nombre Actualizado',$user->fresh()->name); }
    public function test_only_admin_can_change_roles(): void { $admin=User::factory()->create(['role'=>'admin']);$manager=User::factory()->create(['role'=>'gestor']);$resident=User::factory()->create(['role'=>'residente']);$this->actingAs($manager)->patch(route('users.role.update',$resident),['role'=>'auditor'])->assertForbidden();$this->actingAs($admin)->patch(route('users.role.update',$resident),['role'=>'auditor'])->assertRedirect();$this->assertSame('auditor',$resident->fresh()->role); }
    public function test_admin_can_create_users(): void { $admin=User::factory()->create(['role'=>'admin']);$this->actingAs($admin)->post(route('users.store'),['name'=>'Nueva Residente','email'=>'nueva@example.com','role'=>'residente','tower'=>'D','unit'=>'401','password'=>'ClaveSegura123','password_confirmation'=>'ClaveSegura123'])->assertRedirect(route('users.index'));$this->assertDatabaseHas('users',['email'=>'nueva@example.com','role'=>'residente','tower'=>'D','unit'=>'401']); }
    public function test_only_admin_can_edit_and_delete_users(): void { $admin=User::factory()->create(['role'=>'admin']);$manager=User::factory()->create(['role'=>'gestor']);$target=User::factory()->create(['role'=>'residente']);$deleteTarget=User::factory()->create(['role'=>'residente']);$this->actingAs($manager)->get(route('users.edit',$target))->assertForbidden();$this->actingAs($admin)->put(route('users.update',$target),['name'=>'Residente Editada','email'=>'editada@example.com','role'=>'auditor','tower'=>'E','unit'=>'502','password'=>'','password_confirmation'=>''])->assertRedirect(route('users.index'));$this->assertDatabaseHas('users',['id'=>$target->id,'email'=>'editada@example.com','role'=>'auditor']);$this->delete(route('users.destroy',$deleteTarget))->assertRedirect(route('users.index'));$this->assertDatabaseMissing('users',['id'=>$deleteTarget->id]); }
    public function test_auditor_can_view_but_not_update(): void { $auditor=User::factory()->create(['role'=>'auditor']);$pqr=Pqr::factory()->create();$this->actingAs($auditor)->get(route('pqrs.show',$pqr))->assertOk();$this->actingAs($auditor)->get(route('pqrs.edit',$pqr))->assertForbidden(); }
}
