@extends('layouts.app')
@section('titulo', 'Detalle de solicitud')
@section('titulo_pagina', 'Detalle de solicitud')
@section('contenido')
    <section class="page-heading compact detail-heading">
        <div><a class="back-link" href="{{ route('pqrs.index') }}">← Volver al panel</a><span class="eyebrow">PQR-{{ str_pad($pqr->id, 4, '0', STR_PAD_LEFT) }}</span><h1>{{ $pqr->asunto }}</h1><span class="status {{ $pqr->estado }}"><i></i>{{ $pqr->estado_label }}</span></div>
        @can('update', $pqr)<a href="{{ route('pqrs.edit', $pqr) }}" class="button primary">Editar solicitud</a>@endcan
    </section>

    <div class="detail-grid">
        <article class="detail-card main-detail">
            <div class="detail-section"><span class="eyebrow">Descripción</span><h2>Información de la solicitud</h2><p class="description-text">{{ $pqr->descripcion }}</p></div>
            <div class="detail-section"><div class="attachments-heading"><div><span class="eyebrow">Soportes</span><h2>Archivos adjuntos</h2></div><span>{{ $pqr->attachments->count() }} archivo(s)</span></div>
                @forelse($pqr->attachments as $attachment)
                    <a class="attachment-row" href="{{ route('attachments.download', $attachment) }}"><span class="attachment-icon">{{ str_starts_with($attachment->mime_type, 'image/') ? 'IMG' : 'DOC' }}</span><span><strong>{{ $attachment->original_name }}</strong><small>{{ number_format($attachment->size / 1024, 0) }} KB</small></span><span class="download-icon">↓</span></a>
                @empty
                    <div class="empty-attachments"><span>＋</span><p>Esta solicitud no tiene archivos adjuntos.</p></div>
                @endforelse
            </div>
            <div class="detail-section"><div class="attachments-heading"><div><span class="eyebrow">Conversación</span><h2>Respuestas</h2></div><span>{{ $pqr->replies->where('is_draft', false)->count() }} enviada(s)</span></div>
                @forelse($pqr->replies->filter(fn($reply) => !$reply->is_draft || auth()->user()->canManagePqrs()) as $reply)
                    <article class="reply-card {{ $reply->is_draft ? 'draft' : '' }}"><div class="reply-heading"><span class="avatar small">{{ Str::upper(Str::substr($reply->user?->name ?? 'NA', 0, 2)) }}</span><div><strong>{{ $reply->user?->name ?? 'Usuario' }}</strong><small>{{ $reply->is_draft ? 'Borrador' : $reply->sent_at?->diffForHumans() }}</small></div>@if($reply->is_draft)<span class="draft-badge">Borrador</span>@endif</div><p>{{ $reply->body }}</p>@if($reply->attachments)<div class="reply-files">@foreach($reply->attachments as $index => $file)<a href="{{ route('pqrs.replies.download', [$pqr, $reply, $index]) }}">↓ {{ $file['name'] }}</a>@endforeach</div>@endif</article>
                @empty<div class="empty-attachments"><p>Aún no se han registrado respuestas.</p></div>@endforelse
            </div>
            @if(auth()->user()->canManagePqrs())<div class="detail-section reply-editor"><span class="eyebrow">Responder</span><h2>Enviar respuesta al residente</h2><form method="POST" action="{{ route('pqrs.replies.store', $pqr) }}" enctype="multipart/form-data">@csrf @if($templates->isNotEmpty())<div class="field"><label for="responseTemplate">Usar plantilla</label><select id="responseTemplate"><option value="">Seleccionar plantilla</option>@foreach($templates as $template)<option data-body="{{ $template->body }}">{{ $template->name }}</option>@endforeach</select></div>@endif <div class="field"><label for="body">Mensaje</label><textarea id="body" name="body" rows="7" required placeholder="Escribe una respuesta clara y completa...">{{ old('body') }}</textarea>@error('body')<small class="field-error">{{ $message }}</small>@enderror</div><div class="field"><label for="replyAttachments">Adjuntar documentos</label><input id="replyAttachments" name="attachments[]" type="file" multiple></div><div class="reply-actions"><button class="button subtle" name="action" value="draft">Guardar borrador</button><button class="button primary" name="action" value="send" data-confirm="Enviar respuesta" data-confirm-message="La respuesta será visible para el residente y la solicitud cambiará a Respondida.">Enviar respuesta →</button></div></form></div>
            <div class="detail-section internal-comments"><span class="eyebrow">Equipo interno</span><h2>Comentarios privados</h2><p class="section-help">Solo son visibles para el personal autorizado.</p><form method="POST" action="{{ route('pqrs.comments.store',$pqr) }}">@csrf<div class="field"><textarea name="body" rows="3" required placeholder="Agrega una nota para el equipo..."></textarea></div><button class="button subtle">Agregar comentario</button></form><div class="comment-list">@forelse($pqr->internalComments as $comment)<article><span class="avatar small">{{ Str::upper(Str::substr($comment->user?->name??'NA',0,2)) }}</span><div><strong>{{ $comment->user?->name??'Usuario' }}</strong><p>{{ $comment->body }}</p><small>{{ $comment->created_at->diffForHumans() }}</small></div></article>@empty<p class="empty-comment">No hay comentarios internos.</p>@endforelse</div></div>@endif
        </article>
        <aside class="detail-card metadata-card">
            <h2>Datos de radicación</h2>
            <div class="time-counter {{ $pqr->is_overdue ? 'overdue' : '' }}"><span>{{ $pqr->is_overdue ? 'Plazo vencido' : 'Tiempo de atención' }}</span><strong>@if($pqr->remaining_days === null)Sin límite @elseif($pqr->remaining_days < 0){{ abs($pqr->remaining_days) }} días vencida @else{{ $pqr->remaining_days }} días restantes @endif</strong><small>{{ $pqr->elapsed_days }} días desde la radicación</small></div><dl><div><dt>Tipo</dt><dd>{{ $pqr->tipoPqr?->nombre ?? 'Sin tipo' }}</dd></div><div><dt>Responsable</dt><dd>{{ $pqr->assignee?->name ?? 'Sin asignar' }}</dd></div><div><dt>Fecha de radicación</dt><dd>{{ $pqr->fecha_radicacion->translatedFormat('d M Y') }}</dd></div><div><dt>Fecha límite</dt><dd>{{ $pqr->fecha_limite_respuesta?->translatedFormat('d M Y') ?? 'Sin definir' }}</dd></div><div><dt>Radicado por</dt><dd>{{ $pqr->user?->name }}</dd></div></dl>
            @if(auth()->user()->canManagePqrs())<div class="tag-manager"><h2>Etiquetas</h2><form method="POST" action="{{ route('pqrs.tags.sync',$pqr) }}">@csrf @method('PATCH')<div class="tag-options">@foreach($availableTags as $tag)<label style="--tag:{{ $tag->color }}"><input type="checkbox" name="tags[]" value="{{ $tag->id }}" @checked($pqr->tags->contains($tag))>{{ $tag->name }}</label>@endforeach</div><button class="button subtle">Guardar etiquetas</button></form></div>@endif<div class="activity-block"><h2>Historial de actividad</h2><div class="activity-timeline">@forelse($pqr->activities as $activity)<div class="activity-item"><i></i><div><strong>{{ $activity->description }}</strong><span>{{ $activity->user?->name ?? 'Sistema' }} · {{ $activity->created_at->diffForHumans() }}</span></div></div>@empty<div class="activity-item"><i></i><div><strong>Sin actividad registrada</strong></div></div>@endforelse</div></div>
            @if(!auth()->user()->canManagePqrs())<div class="locked-note"><span>⌾</span><p><strong>Solicitud radicada</strong>La información ya no puede ser modificada. El equipo de gestión registrará aquí sus avances.</p></div>@endif @if($pqr->user_id===auth()->id() && in_array($pqr->estado,['respondida','cerrada']))<div class="satisfaction-card"><h2>¿Cómo fue la atención?</h2>@if($pqr->satisfactionSurvey)<strong>{{ str_repeat('★',$pqr->satisfactionSurvey->rating) }}{{ str_repeat('☆',5-$pqr->satisfactionSurvey->rating) }}</strong><p>Gracias por compartir tu opinión.</p>@else<form method="POST" action="{{ route('pqrs.survey.store',$pqr) }}">@csrf<div class="rating-input">@foreach(range(5,1) as $rating)<input id="rating{{ $rating }}" type="radio" name="rating" value="{{ $rating }}" required><label for="rating{{ $rating }}">★</label>@endforeach</div><textarea name="comment" rows="2" placeholder="Comentario opcional"></textarea><button class="button primary">Enviar valoración</button></form>@endif</div>@endif
        </aside>
    </div>
@endsection
