<!DOCTYPE html><html lang="es"><head><meta charset="UTF-8"><style>
@page{margin:25px 28px 30px}*{box-sizing:border-box}body{font-family:DejaVu Sans,sans-serif;color:#24332e;font-size:8px;margin:0}.header{background:{{ $settings->color_principal ?: '#12382f' }};color:#fff;padding:18px 20px;border-radius:8px}.header h1{margin:0 0 4px;font-size:19px}.header h2{margin:0;font-size:11px;font-weight:normal}.meta{margin-top:7px;color:#d6e4df}.company{width:100%;margin:14px 0;border-collapse:collapse}.company td{padding:3px 8px 3px 0}.company b{color:#61716b}.kpis{width:100%;border-spacing:7px;margin:0 -7px 14px}.kpis td{background:#f1f6f3;border-left:4px solid {{ $settings->color_principal ?: '#12382f' }};padding:9px}.kpis span{display:block;color:#66756f;font-size:7px;text-transform:uppercase}.kpis strong{display:block;font-size:17px;margin-top:2px}.section-title{font-size:11px;margin:13px 0 6px;color:{{ $settings->color_principal ?: '#12382f' }};border-bottom:1px solid #dce4e0;padding-bottom:5px}.columns{width:100%;border-spacing:12px 0;margin:0 -12px}.columns>tbody>tr>td{width:50%;vertical-align:top}table.data{width:100%;border-collapse:collapse}table.data th{background:{{ $settings->color_principal ?: '#12382f' }};color:#fff;text-align:left;padding:6px;font-size:7px}table.data td{padding:5px 6px;border-bottom:1px solid #e3e9e6;vertical-align:top}table.data tr:nth-child(even) td{background:#f7f9f8}.status{font-weight:bold}.warning{color:#9b6819}.danger{color:#a33d34}.footer{position:fixed;bottom:-18px;left:0;right:0;color:#718079;font-size:7px;border-top:1px solid #dce4e0;padding-top:5px}.page-break{page-break-before:always}.desc{color:#6b7772;font-size:7px;margin-top:2px}.empty{padding:12px;background:#f7f9f8;color:#6b7772}
</style></head><body>
<header class="header"><h1>{{ $settings->nombre_conjunto }}</h1><h2>Informe de gestión de PQRS</h2><div class="meta">Periodo: {{ $period }} · Generado el {{ $generatedAt->format('d/m/Y \a \l\a\s H:i') }}</div></header>
<table class="company"><tr><td><b>NIT</b><br>{{ $settings->nit ?: 'No registrado' }}</td><td><b>Representante legal</b><br>{{ $settings->representante_legal ?: 'No registrado' }}</td><td><b>Dirección</b><br>{{ $settings->direccion ?: 'No registrada' }} {{ $settings->ciudad }}</td><td><b>Contacto</b><br>{{ $settings->email ?: $settings->telefono ?: 'No registrado' }}</td></tr></table>
<table class="kpis"><tr><td><span>Total del periodo</span><strong>{{ $stats['total'] }}</strong></td><td><span>Pendientes</span><strong>{{ $stats['pending'] }}</strong></td><td><span>Próximas a vencer</span><strong>{{ $stats['upcoming'] }}</strong></td><td><span>Vencidas</span><strong>{{ $stats['overdue'] }}</strong></td><td><span>Gestión completada</span><strong>{{ $stats['compliance'] }}%</strong></td></tr></table>
<table class="columns"><tr><td><h3 class="section-title">Distribución por estado</h3><table class="data"><tr><th>Estado</th><th>Total</th><th>Participación</th></tr>@foreach($byStatus as $status=>$count)<tr><td>{{ Str::headline($status) }}</td><td>{{ $count }}</td><td>{{ $stats['total'] ? round($count/$stats['total']*100) : 0 }}%</td></tr>@endforeach</table></td><td><h3 class="section-title">Distribución por tipo</h3><table class="data"><tr><th>Tipo</th><th>Total</th><th>Participación</th></tr>@foreach($byType as $type=>$count)<tr><td>{{ $type }}</td><td>{{ $count }}</td><td>{{ $stats['total'] ? round($count/$stats['total']*100) : 0 }}%</td></tr>@endforeach</table></td></tr></table>
<h3 class="section-title">Solicitudes próximas a vencer (3 días)</h3>@if($upcoming->isEmpty())<div class="empty">No hay solicitudes próximas a vencer en el periodo seleccionado.</div>@else<table class="data"><tr><th>Radicado</th><th>Fecha límite</th><th>Días</th><th>Asunto</th><th>Residente</th><th>Responsable</th></tr>@foreach($upcoming as $pqr)<tr><td>PQR-{{ str_pad($pqr->id,4,'0',STR_PAD_LEFT) }}</td><td>{{ $pqr->fecha_limite_respuesta->format('d/m/Y') }}</td><td class="warning">{{ $pqr->remaining_days }}</td><td>{{ $pqr->asunto }}</td><td>{{ $pqr->user?->name }}</td><td>{{ $pqr->assignee?->name ?? 'Sin asignar' }}</td></tr>@endforeach</table>@endif
<div class="page-break"></div><h3 class="section-title">Detalle de PQRS del periodo</h3><table class="data"><thead><tr><th>Radicado</th><th>Radicación</th><th>Límite</th><th>Estado</th><th>Tipo</th><th>Asunto</th><th>Residente</th><th>Responsable</th></tr></thead><tbody>@forelse($rows as $pqr)<tr><td>PQR-{{ str_pad($pqr->id,4,'0',STR_PAD_LEFT) }}</td><td>{{ $pqr->fecha_radicacion->format('d/m/Y') }}</td><td class="{{ $pqr->is_overdue ? 'danger' : '' }}">{{ $pqr->fecha_limite_respuesta?->format('d/m/Y') ?? 'Sin fecha' }}</td><td class="status">{{ $pqr->estado_label }}</td><td>{{ $pqr->tipoPqr?->nombre }}</td><td><b>{{ $pqr->asunto }}</b><div class="desc">{{ Str::limit($pqr->descripcion,90) }}</div></td><td>{{ $pqr->user?->name }}</td><td>{{ $pqr->assignee?->name ?? 'Sin asignar' }}</td></tr>@empty<tr><td colspan="8">No hay registros para los filtros seleccionados.</td></tr>@endforelse</tbody></table>
<div class="footer">{{ $settings->nombre_conjunto }} · Informe interno de gestión de PQRS · {{ $generatedAt->format('d/m/Y H:i') }}</div></body></html>
