<?php
namespace App\Http\Controllers;
use App\Application\Contexto\ContextoOperativo;
use App\Application\Pqrs\ConsultaPqrsContextuales;
use App\Models\{AuditLog,AutomationRule,Pqr,PqrTag,ResponseTemplate,SatisfactionSurvey,TipoPqr,User};
use Illuminate\Http\RedirectResponse; use Illuminate\Http\Request; use Illuminate\Validation\Rule; use Illuminate\View\View;
class ComplementaryController extends Controller {
 private function admin(Request $r):void{abort_unless($r->user()->isAdmin(),403);} private function manager(Request $r):void{abort_unless(in_array($r->user()->role,['admin','gestor'],true),403);}
 public function workload(Request $r,ContextoOperativo $contexto,ConsultaPqrsContextuales $consulta):View{$this->manager($r);$scope=fn($q)=>$consulta->restringir($q,$contexto);$users=User::whereIn('role',['admin','gestor','apoyo'])->withCount(['assignedPqrs as active_count'=>fn($q)=>$scope($q)->whereIn('estado',['radicada','en_revision']),'assignedPqrs as overdue_count'=>fn($q)=>$scope($q)->whereIn('estado',['radicada','en_revision'])->whereDate('fecha_limite_respuesta','<',today()),'assignedPqrs as completed_count'=>fn($q)=>$scope($q)->whereIn('estado',['respondida','cerrada'])])->get();return view('management.workload',compact('users'));}
 public function tools(Request $r,ContextoOperativo $contexto):View{$this->manager($r);return view('management.tools',['templates'=>ResponseTemplate::latest()->get(),'tags'=>PqrTag::where('organizacion_id',$contexto->organizacion->id)->where('copropiedad_id',$contexto->copropiedad->id)->orderBy('name')->get(),'rules'=>AutomationRule::with(['type','assignee'])->latest()->get(),'types'=>TipoPqr::orderBy('nombre')->get(),'managers'=>User::whereIn('role',['admin','gestor','apoyo'])->orderBy('name')->get()]);}
 public function template(Request $r):RedirectResponse{$this->manager($r);$d=$r->validate(['name'=>'required|max:100','subject'=>'nullable|max:150','body'=>'required|max:10000']);ResponseTemplate::create($d+['created_by'=>$r->user()->id]);return back()->with('success','Plantilla creada.');}
 public function tag(Request $r,ContextoOperativo $contexto):RedirectResponse{$this->manager($r);$d=$r->validate(['name'=>['required','max:60',Rule::unique('pqr_tags','name')->where(fn($q)=>$q->where('copropiedad_id',$contexto->copropiedad->id))],'color'=>'required|regex:/^#[0-9A-Fa-f]{6}$/']);$tag=new PqrTag($d);$tag->organizacion()->associate($contexto->organizacion);$tag->copropiedad()->associate($contexto->copropiedad);$tag->save();return back()->with('success','Etiqueta creada.');}
 public function rule(Request $r):RedirectResponse{$this->manager($r);AutomationRule::create($r->validate(['name'=>'required|max:100','tipo_pqr_id'=>'nullable|exists:tipo_pqrs,id','assign_to_id'=>'nullable|exists:users,id','set_status'=>'required|in:radicada,en_revision']));return back()->with('success','Regla automática creada.');}
 public function syncTags(Request $r,Pqr $pqr,ContextoOperativo $contexto):RedirectResponse{$this->authorize('update',$pqr);abort_unless($pqr->organizacion_id===$contexto->organizacion->id&&$pqr->copropiedad_id===$contexto->copropiedad->id,404);$d=$r->validate(['tags'=>'nullable|array','tags.*'=>[Rule::exists('pqr_tags','id')->where(fn($q)=>$q->where('organizacion_id',$contexto->organizacion->id)->where('copropiedad_id',$contexto->copropiedad->id))]]);$pqr->tags()->syncWithPivotValues($d['tags']??[],['organizacion_id'=>$contexto->organizacion->id,'copropiedad_id'=>$contexto->copropiedad->id]);$pqr->activities()->create(['user_id'=>$r->user()->id,'action'=>'tags_updated','description'=>'Actualizó las etiquetas de la solicitud.']);return back()->with('success','Etiquetas actualizadas.');}
 public function residents(Request $r):View{$this->admin($r);return view('management.residents',['residents'=>User::where('role','residente')->orderBy('name')->paginate(20)]);}
 public function resident(Request $r,User $user):RedirectResponse{$this->admin($r);$user->update($r->validate(['tower'=>'nullable|max:50','unit'=>'nullable|max:50']));return back()->with('success','Unidad residencial actualizada.');}
 public function audit(Request $r):View{$this->admin($r);return view('management.audit',['logs'=>AuditLog::with('user')->latest()->paginate(30)]);}
 public function survey(Request $r,Pqr $pqr):RedirectResponse{$this->authorize('view',$pqr);abort_unless($pqr->user_id===$r->user()->id&&in_array($pqr->estado,['respondida','cerrada']),403);$d=$r->validate(['rating'=>'required|integer|between:1,5','comment'=>'nullable|max:2000']);SatisfactionSurvey::updateOrCreate(['pqr_id'=>$pqr->id],$d+['user_id'=>$r->user()->id]);return back()->with('success','Gracias por calificar la atención.');}
}
